version: 2
updates:
  # Root package.json
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'gaguero'
    assignees:
      - 'gaguero'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      development-dependencies:
        dependency-type: 'development'
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier'
          - 'typescript'
          - 'turbo'
      security-updates:
        dependency-type: 'production'
        patterns:
          - '*'
        update-types:
          - 'security'

  # Shared package
  - package-ecosystem: 'npm'
    directory: '/packages/shared'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '09:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(shared)'

  # Backend package
  - package-ecosystem: 'npm'
    directory: '/packages/backend'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '09:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(backend)'

  # Web package
  - package-ecosystem: 'npm'
    directory: '/packages/web'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '09:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(web)'

  # Mobile package
  - package-ecosystem: 'npm'
    directory: '/packages/mobile'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '09:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(mobile)'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'ci'
