[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'npm ci',
  'cd packages/backend && npm run build'
]

[start]
cmd = 'npm run start'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
PORT = '8080' 